repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=200']
      - id: double-quote-string-fixer
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint
      args: [
        -e, "SC2028,SC2129"
          # SC2028: suggestion to use printf rather than echo
          # SC2129: style
      ]
