name: Python Project CI

on:
  push:
    branches:  
    - "*" # check on all branches
  pull_request:
    branches:  
    - "*" # check on all branches

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Important: Fetch full git history
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
    
    - name: Run pre-commit checks
      # Continue even if files are modified
      continue-on-error: true
      run: pre-commit run --all-files

    - name: Check for modified files
      id: git-check
      run: |
        # If there are changes, set a flag
        echo "modified=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
    
    - name: Commit changes
      if: steps.git-check.outputs.modified != '0'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Auto-format code with pre-commit hooks"
        git push